posix_thread.c: Avoid assuming tv_sec is a long
It's actually time_t.

This fixes the following warning.
(Fixed partly by this commit, and partly in NuttX. [1])

[1] https://github.com/apache/incubator-nuttx/pull/3039

```
wamr/core/shared/platform/common/posix/posix_thread.c:179:22: error: implicit
      conversion from 'long long' to 'time_t' (aka 'unsigned int') changes value
      from 9223372036854775807 to 4294967295 [-Werror,-Wconstant-conversion]
        ts->tv_sec = LONG_MAX;
                   ~ ^~~~~~~~
/Users/yamamoto/git/nuttx/nuttx/include/arch/limits.h:78:22: note: expanded from
      macro 'LONG_MAX'
                     ^~~~~~~~~~~~~~~~~~~~~
wamr/core/shared/platform/common/posix/posix_thread.c:196:50: error: result of
      comparison of constant 9223372036854775807 with expression of type 'time_t'
      (aka 'unsigned int') is always true
      [-Werror,-Wtautological-constant-out-of-range-compare]
    if (ts->tv_nsec >= 1000000000L && ts->tv_sec < LONG_MAX) {
                                      ~~~~~~~~~~ ^ ~~~~~~~~
```